server:
  port: 8888

spring:
  application:
    name: identity-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

springdoc:
  api-docs:
    path: /identity-service/v3/api-docs
  swagger-ui:
    path: /identity-service/swagger-ui.html