###
GET http://localhost:8765/identities
Content-Type: application/json
Authorization: Basic admin admin

###
@identity-id = 2
DELETE http://localhost:8765/identities/delete/{{identity-id}}
Authorization: Basic user user

###
GET http://localhost:8765/authentication/principal
Authorization: Basic admin admin

###
GET http://localhost:8765/posts/by-identity?identityId=1
Content-Type: application/json
Authorization: Basic admin admin

###
DELETE http://localhost:8765/posts/delete?postId=1&identityId=1
Authorization: Basic admin admin

###
POST http://localhost:8765/posts/create
Content-Type: application/json
Authorization: Basic admin admin

{
  "identityId": 1,
  "content": "Новый пост, который запостил админ"
}

###
PUT http://localhost:8765/posts/update
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 2,
  "identityId": 1,
  "content": "Новый пост, который запостил админ, был успешно изменен?"
}

###
POST http://localhost:8765/comments/create
Content-Type: application/json
Authorization: Basic admin admin

{
  "postId": 1,
  "identityId": 1,
  "content": "Спасибо за комментарий!"
}

###
PUT http://localhost:8765/comments/update
Content-Type: application/json
Authorization: Basic admin admin

{
  "id": 2,
  "postId": 1,
  "identityId": 1,
  "content": "Спасибо за комментарий, просто чел!"
}

###
DELETE http://localhost:8765/comments/delete?commentId=2&identityId=1
Content-Type: application/json
Authorization: Basic admin admin

###
POST http://localhost:8765/messages/send-private-message
Content-Type: application/json
Authorization: Basic admin admin

{
  "content": "Привет, как дела?",
  "senderId": 1,
  "receiverId": 2
}

###
POST http://localhost:8765/messages/send-private-message
Content-Type: application/json
Authorization: Basic user user

{
  "chatId": 1,
  "content": "Привет, да норм, у тебя как?",
  "senderId": 2,
  "receiverId": 1
}

###
GET http://localhost:8765/chats/by-identity/1
Content-Type: application/json
Authorization: Basic admin admin

###
GET http://localhost:8765/chats/1?identityId=2
Content-Type: application/json
Authorization: Basic user user

###
POST http://localhost:8765/identities/create
Content-Type: application/json

{
  "username": "burgasvv",
  "password": "cg3audio",
  "email": "burgasvv@gmail.com",
  "firstname": "Burgas",
  "lastname": "Slava",
  "patronymic": "Vasilich"
}

###
POST http://localhost:8765/friendship/send-friend-request
Content-Type: application/json
Authorization: Basic admin admin

{
  "identityId": 1,
  "friendId": 2
}

###
POST http://localhost:8765/friendship/send-friend-request
Content-Type: application/json
Authorization: Basic admin admin

{
  "identityId": 1,
  "friendId": 3
}

###
GET http://localhost:8765/friendship/by-friend/2?accepted=false
Content-Type: application/json
Authorization: Basic user user

###
GET http://localhost:8765/friendship/by-friend/2?accepted=true
Content-Type: application/json
Authorization: Basic user user

###
POST http://localhost:8765/friendship/accept-friendship
Content-Type: application/json
Authorization: Basic user user

{
  "identityId": 2,
  "friendId": 1
}

###
POST http://localhost:8765/friendship/accept-friendship
Content-Type: application/json
Authorization: Basic burgasvv cg3audio

{
  "identityId": 3,
  "friendId": 1
}

###
GET http://localhost:8765/identities/by-id/1/friends
Content-Type: application/json
Authorization: Basic admin admin

###
POST http://localhost:8765/friendship/decline-friendship
Content-Type: application/json
Authorization: Basic user user

{
  "identityId": 2,
  "friendId": 1
}

###
DELETE http://localhost:8765/friendship/delete-from friendship
Content-Type: application/json
Authorization: Basic burgasvv cg3audio

{
  "identityId": 3,
  "friendId": 1
}

###
POST http://localhost:8765/communities/create?identityId=1
Content-Type: application/json
Authorization: Basic admin admin

{
  "title": "Java Programmer",
  "description": "New java community for you",
  "isPublic": true,
  "openPost": true,
  "openComment": true
}

###
POST http://localhost:8765/communities/join-the-community
Content-Type: application/json
Authorization: Basic user user

{
  "identityId": 2,
  "communityId": 1
}

###
POST http://localhost:8765/communities/leave-the-community
Content-Type: application/json
Authorization: Basic user user

{
  "identityId": 2,
  "communityId": 1
}

###
GET http://localhost:8765/communities/on-identity/2
Content-Type: application/json
Authorization: Basic user user

###
GET http://localhost:8765/identities/in-community?identityId=1&communityId=1
Content-Type: application/json
Authorization: Basic admin admin

###
GET http://localhost:8765/communities/1
Content-Type: application/json
Authorization: Basic user user