server:
  port: 9000

spring:
  application:
    name: post-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

springdoc:
  api-docs:
    path: /post-service/v3/api-docs
  swagger-ui:
    path: /post-service/swagger-ui.html